# Generated by Django 3.1.3 on 2021-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='views_coiunt',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
